### ISSUE TITLE
Comparisons of the Performance API

### ISSUE THREAD

**Issue by Grunet** [worker-tools/workers.js.org#2]
[This](https://developer.mozilla.org/en-US/docs/Web/API/Performance) Web Performance API, since it's just so generically named...

Would you be interested in having a line for that in the Browser APIs compatibility comparison? 

I just learned today that Cloudflare Workers doesn't support it (or any of the other timing mechanisms for that) whereas Deno Deploy does, which (at least imo) seems like an important distinction for those trying to profile/understand the workers' behavior.

Also fwiw I'm not sure about the last 4 columns, but I believe Service Workers and Deno CLI do support it (though I'd need to double check).

(Really like your site btw! Was very helpful in orienting me when I was first learning about this stuff)

**Comment by qwtel** [comment]
Hi, I wasn't aware that Deno really does support it (even Deno CLI). Would certainly be good to have one row dedicated to it.

**Comment by qwtel** [comment]
> Also fwiw I'm not sure about the last 4 columns

I'm close to removing a couple of columns since they are either already abandoned or made obsolete by Miniflare (now included in wrangler). If you intend to open a PR, you can leave a question mark there.
